-- ============================================================
-- Migration 006 : Seed massif d'exercices globaux
-- ============================================================
-- Source : liste fournie par l'utilisateur (exo.txt) — environ 145 entrées
-- Toutes insérées avec coach_id = NULL → exercices "système" partagés.
-- Mapping de catégories (lib RTS → schéma exercises) :
--   Knee Dominant   → Squat
--   Hip Dominant    → Hinge
--   Horizontal Push → Horizontal Push
--   Horizontal Pull → Horizontal Pull
--   Vertical Push   → Vertical Push
--   Vertical Pull   → Vertical Pull
--   Misc            → Accessoire (sauf Run / Row Erg / Assault Bike → Cardio)
--   Weightlifting   → Accessoire
--   User Defined    → Accessoire
--
-- Idempotent : skip si (name, coach_id IS NULL) existe déjà.

INSERT INTO exercises (name, category, coach_id)
SELECT v.name, v.category::text, NULL
FROM (VALUES
  ('45° Back Raise',                             'Hinge'),
  ('Ab Wheel',                                   'Accessoire'),
  ('Abduction Machine',                          'Accessoire'),
  ('Abs (choice)',                               'Accessoire'),
  ('Adduction Machine',                          'Accessoire'),
  ('Assault Bike',                               'Cardio'),
  ('Atlas Stone',                                'Vertical Pull'),
  ('Axle Press',                                 'Vertical Push'),
  ('Back Extensions',                            'Hinge'),
  ('Bench Press',                                'Horizontal Push'),
  ('Bulgarian Split Squat',                      'Squat'),
  ('Burger manger',                              'Accessoire'),
  ('Burpees Broad Jump',                         'Cardio'),
  ('Bus Drivers',                                'Accessoire'),
  ('BW Bulgarian Split Squat',                   'Squat'),
  ('BW Dips',                                    'Vertical Push'),
  ('BW Lunges',                                  'Squat'),
  ('BW Pull Up',                                 'Vertical Pull'),
  ('BW Single Leg Hip Thrusters',                'Hinge'),
  ('BW Single Leg RDL',                          'Hinge'),
  ('Cable Curtsy Glute Kickbacks',               'Hinge'),
  ('Cable Glute Kickbacks',                      'Hinge'),
  ('Cable Pull Through',                         'Hinge'),
  ('Cable Row',                                  'Horizontal Pull'),
  ('Calf Raise',                                 'Accessoire'),
  ('Chest Supported Row',                        'Horizontal Pull'),
  ('circuit',                                    'Accessoire'),
  ('Clean',                                      'Accessoire'),
  ('Clean & Jerk',                               'Accessoire'),
  ('Clean High Pull',                            'Accessoire'),
  ('Clean Pull',                                 'Accessoire'),
  ('Clean Pull + 2 Cleans',                      'Accessoire'),
  ('Clean Pull + Clean',                         'Accessoire'),
  ('Clean Pull + Floating Clean + Clean',        'Accessoire'),
  ('Contralateral Rotational B-Stance Romanian Deadlift', 'Hinge'),
  ('Copenhagen Plank',                           'Accessoire'),
  ('Curls',                                      'Accessoire'),
  ('Deadlift (conv)',                            'Hinge'),
  ('Deadlift (sumo)',                            'Hinge'),
  ('Decline Bench Press',                        'Horizontal Push'),
  ('Dips',                                       'Vertical Push'),
  ('Drop Snatch',                                'Accessoire'),
  ('Elbows Out Extension',                       'Horizontal Push'),
  ('Flies',                                      'Horizontal Push'),
  ('Floor Press',                                'Horizontal Push'),
  ('Frankenstein Squat',                         'Squat'),
  ('Front Foot Elevated Split Squat',            'Squat'),
  ('Front Rack Hold',                            'Accessoire'),
  ('Front Raise',                                'Accessoire'),
  ('Front Squat',                                'Squat'),
  ('GHD hip lateral flexion',                    'Accessoire'),
  ('GHD Side Bends',                             'Accessoire'),
  ('Glute Ham Raise',                            'Hinge'),
  ('Glute Step-Ups',                             'Hinge'),
  ('Goblet Squat',                               'Squat'),
  ('Good Morning',                               'Hinge'),
  ('Hack Squat',                                 'Squat'),
  ('Handstand Push Up',                          'Vertical Push'),
  ('Hatfield Squat',                             'Squat'),
  ('Hip Belt Squat',                             'Squat'),
  ('Hip Thrust',                                 'Hinge'),
  ('Husafell Carry',                             'Accessoire'),
  ('Incline Bench',                              'Horizontal Push'),
  ('Incline Curl',                               'Accessoire'),
  ('Incline Push Up',                            'Horizontal Push'),
  ('Incline Row',                                'Horizontal Pull'),
  ('Inverted Rows',                              'Horizontal Pull'),
  ('J.M. Press',                                 'Horizontal Push'),
  ('Jerk',                                       'Accessoire'),
  ('Jerk Dip Squat',                             'Accessoire'),
  ('Jump Squat',                                 'Squat'),
  ('Landmine Press',                             'Vertical Push'),
  ('Landmine Rotation',                          'Accessoire'),
  ('Lateral Raise',                              'Accessoire'),
  ('Leg Curls',                                  'Hinge'),
  ('Leg Extensions',                             'Squat'),
  ('Leg Lowers',                                 'Accessoire'),
  ('Leg Press',                                  'Squat'),
  ('Lever Row',                                  'Horizontal Pull'),
  ('Log Press',                                  'Vertical Push'),
  ('Lunges',                                     'Squat'),
  ('Machine Press',                              'Horizontal Push'),
  ('Manual Hamstring Curl',                      'Hinge'),
  ('Meadows Row',                                'Horizontal Pull'),
  ('Neutral Grip Incline Press',                 'Vertical Push'),
  ('One Arm Row',                                'Horizontal Pull'),
  ('Overhead Squat',                             'Squat'),
  ('Pallof Press',                               'Accessoire'),
  ('Pendlay Row',                                'Horizontal Pull'),
  ('Pike Row',                                   'Vertical Pull'),
  ('Plank',                                      'Accessoire'),
  ('Platz Squat',                                'Squat'),
  ('Power Jerk + Split Jerk',                    'Accessoire'),
  ('Pressing Snatch Balance',                    'Accessoire'),
  ('Pull Down',                                  'Vertical Pull'),
  ('Pull Over',                                  'Vertical Pull'),
  ('Pull Up',                                    'Vertical Pull'),
  ('Push Jerk',                                  'Accessoire'),
  ('Push Press',                                 'Vertical Push'),
  ('Push Press + Power Jerk + Split Jerk',       'Accessoire'),
  ('Push Up',                                    'Horizontal Push'),
  ('Rear Delt Flies',                            'Horizontal Pull'),
  ('Reverse Grip Bench',                         'Horizontal Push'),
  ('Reverse Hyper',                              'Hinge'),
  ('Reverse Lunges',                             'Squat'),
  ('Romanian Deadlift',                          'Hinge'),
  ('Rope Climbing',                              'Vertical Pull'),
  ('Row',                                        'Horizontal Pull'),
  ('Row Erg',                                    'Cardio'),
  ('Run',                                        'Cardio'),
  ('Séance au choix',                            'Accessoire'),
  ('Seated Military',                            'Vertical Push'),
  ('Seated Zercher Good Morning',                'Hinge'),
  ('Shrugs',                                     'Vertical Push'),
  ('Side Lunges',                                'Squat'),
  ('Side Plank',                                 'Accessoire'),
  ('Side Steps with Hip Circle/Resistance Band', 'Accessoire'),
  ('Single Leg RDL',                             'Hinge'),
  ('SISI SQUAT',                                 'Squat'),
  ('Sit Up',                                     'Accessoire'),
  ('Sled Push',                                  'Squat'),
  ('Snatch',                                     'Accessoire'),
  ('Snatch Balance',                             'Accessoire'),
  ('Snatch High Pull',                           'Accessoire'),
  ('Snatch Pull',                                'Accessoire'),
  ('Snatch Pull + 2 Snatches',                   'Accessoire'),
  ('Snatch Pull + Floating Snatch + Snatch',     'Accessoire'),
  ('Snatch Pull + Snatch',                       'Accessoire'),
  ('Split Squat',                                'Squat'),
  ('Squat',                                      'Squat'),
  ('Standing Military',                          'Vertical Push'),
  ('Star Plank',                                 'Hinge'),
  ('Step Ups',                                   'Squat'),
  ('Stiff Leg Deadlift',                         'Hinge'),
  ('T-Bar Row',                                  'Horizontal Pull'),
  ('Top of the ring hold',                       'Vertical Push'),
  ('Tricep Extensions',                          'Horizontal Push'),
  ('Tricep Pushdowns',                           'Horizontal Push'),
  ('Upright Row',                                'Vertical Pull'),
  ('Vertical Pull',                              'Vertical Pull'),
  ('Wall Sit',                                   'Squat'),
  ('Wide Grip Chin Up (pronated)',               'Vertical Pull'),
  ('Zercher Carry',                              'Accessoire'),
  ('Zercher Jefferson Curl',                     'Hinge'),
  ('Zercher Squat',                              'Squat'),
  ('Zombie squat',                               'Squat')
) AS v(name, category)
WHERE NOT EXISTS (
  SELECT 1 FROM exercises e
  WHERE e.name = v.name AND e.coach_id IS NULL
);
